stages:
  - create_stage_environment
  - setup_stage_environment
  - test
  - delete_stage_environment

create_stage:
  stage: create_stage_environment
  image:
    name: hashicorp/terraform:light
    entrypoint:
      - /usr/bin/env
  script:
    - echo $SERVICEACCOUNT | base64 -d > vodomat_key.json
    - echo $SSH_PUBLIC_KEY > vodomat.pub
    - terraform init
    - terraform apply -auto-approve
    - terraform output server_external_ip > server_external_ip
  artifacts:
    paths:
      - .terraform
      - terraform.tfstate
      - server_external_ip
    expire_in: 1 week

setup_stage:
  stage: setup_stage_environment
  image:
    name: ansible/centos7-ansible:latest
  script: 
    - export SERVER_EXTERNAL_IP = $(cat server_external_ip)
    - ansible -i $SERVER_EXTERNAL_IP -a ping
  dependencies:
    - create_stage

test_application:
  stage: test
  script: echo "Test app"

test_api:
  stage: test
  script: echo "Test api"

delete_stage:
  stage: delete_stage_environment
  script:
    - echo $SERVICEACCOUNT | base64 -d > vodomat_key.json
    - echo $SSH_PUBLIC_KEY > vodomat.pub
    - terraform destroy -auto-approve
  dependencies:
    - create_stage
  when: manual