stages:
  - create_stage_environment
  - test
  - delete_stage_environment

create_stage:
  stage: create_stage_environment
  image: 
    name: hashicorp/terraform:light
    entrypoint:
      - '/usr/bin/env'
      - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
  script:
    - echo $SERVICEACCOUNT | base64 -d > ./vodomat_key.json
    - terraform init
    - terraform apply -auto-approve
  artifacts:
    paths:
      - terraform.tfstate
      - .terraform
      - vodomat_key.json
    expire_in: 3 day

setup_stage:
  stage: create_stage_environment
  script: echo "Set up"

test_application:
  stage: test
  script: echo "Test app"

test_api:
  stage: test
  script: echo "Test api"

delete_stage:
  stage: delete_stage_environment
  image:
    name: hashicorp/terraform:light
    entrypoint:
      - '/usr/bin/env'
      - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
  script:
    - terraform destroy -auto-approve
  dependencies:
    - create_stage
  when: manual