before_script:
  - echo $SERVICEACCOUNT | base64 -d > ./vodomat_key.json

stages:
  - create_stage_environment
  - test
  - delete_stage_environment

create_stage:
  stage: create_stage_environment
  image: 
    name: hashicorp/terraform:light
    entrypoint:
      - '/usr/bin/env'
      - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
  script:
    - pwd
    - ls -a
    - terraform init
    - terraform apply -input=false

setup_stage:
  stage: create_stage_environment
  script: echo "Set Up"

test_application:
  stage: test
  script: echo "Test app"

test_api:
  stage: test
  script: echo "Test api"

delete_stage:
  stage: delete_stage_environment
  script: echo "Delete"
  when: manual